# ========================================================================================================
#             EXEMPLO DE PROGRAMA EM MIPS PARA ILUSTRAR E/S E ALGUMAS OPERA?OES ARITMETICAS
#
# NO MIPS, OS COMENTARIOS SAO FEITOS USANDO O #
# COMO VOCES JA SABEM, COMENTARIOS DOCUMENTAM O CODIGO MAS SAO IGNORADOS PELO COMPILADOR
#
#		              @PROF. JEAN LAINE - ORG. DE COMPUTADORES - FCI
# ========================================================================================================

.data
# .data EH O SEGMENTO ONDE DECLARAMOS AS "VARIAVEIS"

N1: .asciiz "Digite o 1o numero: "
N2: .asciiz "Digite o 2o numero: "
MsgSoma: .asciiz "\nSoma = "
MsgSub: .asciiz "\nSubtracao = "
MsgMul: .asciiz "\nMultiplicacao = "
MsgDiv: .asciiz

.text
# .text EH O SEGMENTO QUE CONTEM AS INSTRUCOES/PROGRAMA

# EM ASSEMBLY, A SYSCALL EH UTILIZADA PARA VARIAS ACOES: LER DADOS DO TECLADO, IMPRIMIR ALGO NA TELA, FINALIZAR O PROGRAMA, ETC
# USE O BOTAO INTERROGACAO DO MARS (?) PARA CONHECER OS CODIGOS DE CONTROLE DAS VARIAS CHAMADAS. SE PREFERIR ACESSE ESTE LINK:
# https://courses.missouristate.edu/kenvollmar/mars/help/syscallhelp.html

# IMPRIMIR A MENSAGEM N1 NA TELA
li $v0,4 # ATRIBUINDO O VALOR 4 PARA O REG $v0 (COD 4: INDICA PRINT DE STRING P/ SYSCALL)
la $a0,N1 # CARREGANDO O END. DA VAR N1 PARA DENTRO DO REGISTRADOR a0
syscall #SYSCALL CHAMA O SO PARA EXECUTAR A ACAO RELATIVA AO CODIGO QUE ESTA NO $v0

# LER UM INTEIRO DIGITADO PELO USUARIO
li $v0,5 # ATRIBUINDO O VALOR 5 PARA O REG $v0 (COD 5: INDICA INPUT DE INT P/ SYSCALL) 
syscall

# FAZER UMA COPIA DO DADO LIDO
move $t0, $v0 # COPIANDO O CONTEUDO DE $v0 PARA $t0

# IMPRIMIR A MENSAGEM N2 NA TELA
li $v0,4 # ATRIBUINDO O CONTE?DO DO $v0 PARA 4 (PRINT)
la $a0,N2
syscall

# LER UM INTEIRO DIGITADO PELO USUARIO
li $v0,5 # ATRIBUINDO O VALOR 5 PARA O REG $v0 (COD 5: INDICA INPUT DE INT P/ SYSCALL) 
syscall

# FAZER COPIA DO DADO LIDO
move $t1, $v0 # COPIANDO O CONTEUDO DE $v0 PARA $t1

# SOMA $t0 COM $t1 E ARMAZENA O RESULTADO EM $t2
add $t2, $t0, $t1
# add EH A OPERACAO DE ADICAO
# $t2 ? O REGISTRADOR DE DESTINO
# $t0 E $t1 S?O OS REGISTRADORES DAS VARIAVEIS N1 E N2

# IMPRIMIR A MENSAGEM DE SOMA = NA TELA
li $v0,4
la $a0,MsgSoma
syscall

# IMPRIMIR O RESULTADO NA TELA
li $v0,1
move $a0, $t2
syscall

# SUBTRACAO $t0 COM $t1 E ARMAZENA O RESULTADO EM $t2
sub $t2, $t0, $t1
# sub EH A OPERACAO DE SUBTRACAO
# $t2 ? O REGISTRADOR DE DESTINO
# $t0 E $t1 S?O OS REGISTRADORES DAS VARIAVEIS N1 E N2

# IMPRIMIR A MENSAGEM DE RESPOSTA NA TELA
li $v0,4
la $a0,MsgSub
syscall

# IMPRIMIR O RESULTADO NA TELA
li $v0,1
move $a0, $t2
syscall

# MULTIPLICACAO $t0 COM $t1 E ARMAZENA O RESULTADO EM $t2
mul $t2, $t0, $t1
# mul EH A OPERACAO DE MULTIPLICACAO
# $t2 ? O REGISTRADOR DE DESTINO
# $t0 E $t1 S?O OS REGISTRADORES DAS VARIAVEIS N1 E N2

# IMPRIMIR A MENSAGEM DE RESPOSTA NA TELA
li $v0,4
la $a0,MsgMul
syscall

# IMPRIMIR O RESULTADO NA TELA
li $v0,1
move $a0, $t2
syscall

# DIVIDIR N1 E N2
div $t2, $t0,$t1
# mul EH A OPERACAO DE MULTIPLICACAO
# $t2 ? O REGISTRADOR DE DESTINO
# $t0 E $t1 S?O OS REGISTRADORES DAS VARIAVEIS N1 E N2

# IMPRIMIR A MENSAGEM DE RESPOSTA NA TELA
li $v0,4
la $a0,MsgDiv	
syscall

# IMPRIMIR O RESULTADO NA TELA
li $v0,1
move $a0, $t2
syscall

li $v0, 10	# 10 ? O COD. QUE A SYSCALL USA PARA ENCERRAR O PROGRAMA
syscall		# SYSCALL CHAMA O SO PARA EXECUTAR A ACAO RELATIVA AO CODIGO QUE ESTA NO $v0

# :-)
